name: Start Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - test
          - demo
          - prod

jobs:
  process-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log environment
        run: echo "Selected environment: ${{ github.event.inputs.environment }}"

      - name: Set environment secrets
        run: |
          if [ "${{ github.event.inputs.environment }}" = "dev" ]; then
            echo "ENV_SECRETS=${{ secrets.DEV_SECRETS }}" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" = "test" ]; then
            echo "ENV_SECRETS=${{ secrets.TEST_SECRETS }}" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" = "demo" ]; then
            echo "ENV_SECRETS=${{ secrets.DEMO_SECRETS }}" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" = "prod" ]; then
            echo "ENV_SECRETS=${{ secrets.PROD_SECRETS }}" >> $GITHUB_ENV
          fi

      - name: Run bash script
        run: |
          echo "Environment secrets value: ${{ env.ENV_SECRETS }}" 