name: Start Environment Using Terraform Cloud

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - test
          - demo
          - prod

jobs:
  process-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }} # TFC API Token



      - name: Run Terraform
        run: |
          cd terraform/${{ github.event.inputs.environment }}
          # Create a backend.tf on the fly for CI mode, or ensure your code has it configured
          # to use the 'remote' backend pointing to your TFC org and the specific workspace.
          cat <<EOF > backend.tf
          terraform {
            cloud {
              organization = "DemoRomitOrg"
              workspaces {
                name = "Workflow-Runner-Test"
              }
            }
          }
          EOF
          terraform init -input=false
          terraform plan -input=false
          terraform apply -auto-approve -input=false
